//! The About window every GNOME app has, and what it owes other people.
//!
//! Two jobs. The first is saying what this program is and who wrote it. The
//! second is the acknowledgements: Sieve is a few thousand lines of its own on
//! top of three hundred crates of other people's work, and the licences those
//! are offered under carry conditions. Listing them is both the polite thing
//! and the required one.

use adw::prelude::*;
use relm4::adw;
use relm4::gtk;

/// Every crate Sieve links: name, version, licence, repository, tab-separated.
///
/// Generated by `scripts/licenses.sh` from `cargo metadata` rather than
/// maintained by hand. A hand-written list is wrong within a week, and the
/// repository links come from each crate's own manifest rather than from
/// somebody's memory of where it lives.
const THIRD_PARTY: &str = include_str!("../data/third-party.txt");

/// One dependency, as the About window shows it.
pub struct Crate<'a> {
    pub name: &'a str,
    pub version: &'a str,
    pub licence: &'a str,
    pub repository: &'a str,
}

/// The pieces doing the actual work, keyed by the crate that carries them.
///
/// "309 crates" tells a reader nothing about what they are running; these are
/// the ones worth naming, with what each is for. Everything else is in the
/// full list.
const NAMED: &[(&str, &str, &str)] = &[
    (
        "bdk_wallet",
        "BDK",
        "Descriptors, coin selection and transaction building — the wallet's understanding of \
         what a wallet is.",
    ),
    (
        "bdk_kyoto",
        "BDK Kyoto",
        "Binds the compact block filter node to BDK's wallets.",
    ),
    (
        "bip157",
        "Kyoto",
        "The node itself: block headers, compact filters, and the peer connections that fetch \
         them. This is what lets Sieve sync without telling a server which addresses are yours.",
    ),
    (
        "relm4",
        "Relm4",
        "The Elm-shaped architecture the interface is built in.",
    ),
    ("gtk4", "GTK", "The toolkit."),
    (
        "libadwaita",
        "libadwaita",
        "The GNOME platform library, and its design language.",
    ),
    (
        "async-hwi",
        "async-hwi",
        "Talking to hardware signers over USB, in Rust — no Python, no daemon.",
    ),
    (
        "argon2",
        "Argon2 (RustCrypto)",
        "Turns your password into a key slowly enough that guessing is expensive.",
    ),
    (
        "chacha20poly1305",
        "XChaCha20-Poly1305 (RustCrypto)",
        "Seals the recovery phrase, and proves the file has not been tampered with.",
    ),
    (
        "rusqlite",
        "SQLite, via rusqlite",
        "Where each derivation path's public descriptors and transaction history live.",
    ),
    (
        "ureq",
        "ureq",
        "The only HTTP client here — prices and, if asked for, fee rates.",
    ),
    (
        "qrcode",
        "qrcode-rust",
        "Draws the code on the receive screen.",
    ),
];

/// Not a crate, so it is not in `cargo metadata` — but it ships in the Flatpak
/// and runs as a child process, which is exactly the sort of thing an
/// acknowledgement is for.
const TOR: (&str, &str, &str) = (
    "Tor",
    "https://gitlab.torproject.org/tpo/core/tor",
    "Bundled so that using Tor does not require installing anything first. Started as a child \
     process and spoken to over SOCKS; never linked into this program.",
);

/// Read the generated list.
pub fn crates() -> Vec<Crate<'static>> {
    THIRD_PARTY
        .lines()
        .filter(|line| !line.trim().is_empty())
        .filter_map(|line| {
            let mut fields = line.split('\t');
            Some(Crate {
                name: fields.next()?,
                version: fields.next()?,
                licence: fields.next()?,
                repository: fields.next().unwrap_or_default(),
            })
        })
        .collect()
}

/// Show it, parented to whatever is on screen.
pub fn present(parent: &impl IsA<gtk::Widget>) {
    let about = adw::AboutDialog::new();
    about.set_application_name("Sieve");
    about.set_application_icon(crate::APP_ID);
    about.set_version(env!("CARGO_PKG_VERSION"));
    about.set_developer_name("Galaxoid Labs");
    about.set_copyright("© 2026 Galaxoid Labs");

    // What it is, in the terms it was built on. Anyone opening this window is
    // deciding whether to trust the thing with money.
    about.set_comments(
        "A Bitcoin wallet that keeps its business to itself.\n\n\
         Sieve syncs by downloading compact block filters and matching them on this machine, \
         so no server is ever told which addresses are yours. Your recovery phrase is sealed \
         with a password you choose and is decrypted only at the moment of signing. Every \
         connection can be routed through Tor, including the ones for prices and fees.",
    );

    // Dual-licensed, which no single `License` value says.
    about.set_license_type(gtk::License::Custom);
    about.set_license(
        "Sieve is offered under your choice of the MIT licence or the Apache Licence 2.0.\n\n\
         It comes with no warranty of any kind. It is software that handles money; read the \
         source, and do not trust it with more than you can afford to lose.",
    );

    let all = crates();
    let find = |name: &str| all.iter().find(|c| c.name == name);

    // Credits, as rows that open the project they name. libadwaita renders
    // "Name https://url" as a link row, which is what makes this a list of
    // places to go rather than a wall of text.
    let mut built_on: Vec<String> = Vec::with_capacity(NAMED.len() + 1);
    for (key, shown, _) in NAMED {
        match find(key) {
            Some(found) if !found.repository.is_empty() => {
                built_on.push(format!("{shown} {}", found.repository));
            }
            // Still named, still thanked, just not clickable.
            _ => built_on.push((*shown).to_string()),
        }
    }
    built_on.push(format!("{} {}", TOR.0, TOR.1));
    let built_on: Vec<&str> = built_on.iter().map(String::as_str).collect();
    about.add_acknowledgement_section(Some("Built on"), &built_on);

    // Legal: one section per named component, so each licence sits with the
    // thing it applies to and says what that thing does here.
    for (key, shown, what) in NAMED {
        let (licence, version) = match find(key) {
            Some(found) => (found.licence, found.version),
            None => continue,
        };
        about.add_legal_section(
            &format!("{shown} {version}"),
            Some(what),
            gtk::License::Custom,
            Some(licence),
        );
    }
    about.add_legal_section(
        TOR.0,
        Some(TOR.2),
        gtk::License::Custom,
        Some("BSD-3-Clause"),
    );

    // Then everything, because the named ones are a choice and the licences
    // apply to all of it.
    let mut rest = String::new();
    for found in &all {
        rest.push_str(&format!(
            "{} {} — {}\n",
            found.name, found.version, found.licence
        ));
    }
    about.add_legal_section(
        &format!("All {} Rust crates", all.len()),
        Some("Every crate this program links, and the licence each is offered under."),
        gtk::License::Custom,
        Some(&rest),
    );

    about.present(Some(parent));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_generated_list_parses_and_looks_whole() {
        // A build that quietly lost or malformed the file would ship an About
        // window acknowledging nobody.
        let all = crates();
        assert!(
            all.len() > 100,
            "the crate list looks truncated: {}",
            all.len()
        );
        assert!(
            all.iter()
                .all(|c| !c.name.is_empty() && !c.version.is_empty())
        );
        // Every crate says something about its licence, including the two that
        // state it in a file rather than in their manifest.
        assert!(
            all.iter()
                .all(|c| !c.licence.is_empty() && c.licence != "unstated"),
            "a crate has no licence recorded"
        );
    }

    #[test]
    fn every_named_component_is_actually_a_dependency() {
        // The names shown in About are hand-written; the versions and licences
        // beside them are not. A rename upstream would otherwise drop a
        // component out of the window without anyone noticing.
        let all = crates();
        for (key, shown, _) in NAMED {
            assert!(
                all.iter().any(|c| &c.name == key),
                "About names {shown} ({key}), which is not a dependency any more"
            );
        }
    }
}
